name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: "1.12.3"
          otp-version: "24.1"
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install Hex locally
        run: mix local.hex --force
      - name: Fetch a copy of rebar
        run: mix local.rebar --force
      - name: Install dependencies
        run: mix deps.get
      - name: Compile source files
        run: mix compile --warnings-as-errors --force
      - name: Run all tests
        run: mix coveralls.json
      - name: Run code analysis
        run: mix credo -a
      - name: Formats the given files
        run: mix format --check-formatted
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
